### ISSUE TITLE
Can't working for udp sometimes.

### ISSUE THREAD

**Issue by hs1512** [kolyvan/kxtorrent#2]
Can't working for udp sometimes.

send announce request 'started' to udp://tracker.openbittorrent.com:80/announce
complete announce request 'started', Error Domain=GCDAsyncSocketErrorDomain Code=3 "Attempt to connect to host timed out" UserInfo=0xc15ff40 {NSLocalizedDescription=Attempt to connect to host timed out}

Why don't working?

**Comment by kolyvan** [comment]
Sorry, but UDP trackers is not supported, at all.
